# deployment-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
  namespace: webapps  # Must match the namespace in your CD pipeline
  labels:
    app: shopping-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: alacherif10/shopping:latest  # Image built in your CI pipeline
        imagePullPolicy: Always  # Ensure the latest image is pulled
        ports:
        - containerPort: 8070  # Port your app listens on
        # Add environment variables if needed (e.g., for databases):
        # env:
        # - name: DB_HOST
        #   value: "db-service"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: webapps
spec:
  type: NodePort  # Use LoadBalancer for AWS ELB integration
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 80      # Expose port 80 externally
      targetPort: 8070  # Maps to the container port
      # nodePort: 30000  # Optional: Uncomment to set a static NodePort
